In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [3]:
print(x+y)
print(np.add(x,y))

[ 6  8 10 12]
[ 6  8 10 12]


In [4]:
print(x-y)
print(np.subtract(x,y))
print(x * y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [13]:
X = np.array([1,2,3,4]).reshape(2,2)
print(X)

[[1 2]
 [3 4]]


In [14]:
y = np.array([5,6,7,8]).reshape(2,2)
print(y)

[[5 6]
 [7 8]]


In [15]:
print(X+y)

[[ 6  8]
 [10 12]]


In [9]:
x = [1,2,3,4]
print(x)

[1, 2, 3, 4]


In [10]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [11]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [16]:
print(X)

[[1 2]
 [3 4]]


In [17]:
print('average of all:',X.mean())

average of all: 2.5


In [18]:
print('average of columns:',X.mean(axis = 0))
print('average of rows:',X.mean(axis = 1))

average of columns: [2. 3.]
average of rows: [1.5 3.5]


In [20]:
X.std()

1.118033988749895

In [22]:
np.median(X)

2.5

In [23]:
X.max()

4

In [24]:
X.min()

1

In [25]:
print(X)

[[1 2]
 [3 4]]


In [26]:
print(3 + X)

[[4 5]
 [6 7]]


In [28]:
print(X -3)

[[-2 -1]
 [ 0  1]]


In [31]:
Y = np.arange(9).reshape(3,3)
print(Y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
x = np.arange(3)
print(x)

[0 1 2]


In [33]:
print(Y + x)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]
