In [1]:
import numpy as np

In [2]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
print(x[x > 10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [4]:
print(x[x <= 7])

[0 1 2 3 4 5 6 7]


In [7]:
print(x[(x > 10) & (x < 17)])

[11 12 13 14 15 16]


In [9]:
x[(x > 10) & (x < 17)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [17]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

# print(np.intersectid(x,y))
# print(np.setdiff(x,y))
# print(np.unionid(x,y))

In [23]:
x = np.random.randint(1,11,size=(10,))
print(x)

[10 10  3  6  4 10  4  9  4 10]


In [25]:
print(np.sort(np.unique(x)))
print(np.sort(x))
print(x)

[ 3  4  6  9 10]
[ 3  4  4  4  6  9 10 10 10 10]
[10 10  3  6  4 10  4  9  4 10]


In [26]:
x.sort()
print(x)

[ 3  4  4  4  6  9 10 10 10 10]


In [27]:
x = np.random.randint(1,11, size=(5,5))
print(x)

[[ 2  4  5  3 10]
 [ 5  8  5  3  7]
 [ 1  6  5  1  3]
 [ 3  2  7  6  4]
 [ 2  5  7  3  3]]


In [28]:
print(np.sort(x,axis = 0))

[[ 1  2  5  1  3]
 [ 2  4  5  3  3]
 [ 2  5  5  3  4]
 [ 3  6  7  3  7]
 [ 5  8  7  6 10]]


In [29]:
print(np.sort(x,axis = 1))

[[ 2  3  4  5 10]
 [ 3  5  5  7  8]
 [ 1  1  3  5  6]
 [ 2  3  4  6  7]
 [ 2  3  3  5  7]]


In [31]:
y = np.arange(1,26)
X = np.reshape(y,(5,5))
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [32]:
Y = x[x % 2 != 0]
print(Y)

[5 3 5 5 3 7 1 5 1 3 3 7 5 7 3 3]
