In [1]:
import numpy as np

In [2]:
# indexing always start with zero,so 1:4 is the second column
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
z = x[1:4, 2:5]
# [1:4] is the column(vertical) [2:5] is row(horizontal)
# slicing 1:4 means getting the 1-3
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [7]:
z = x[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [18]:
z = x[:3, 2:]
# :3 will get the last three colums(vertical)
# no counting from zeros
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [20]:
z = x[:,2]
print(z)

[ 3  8 13 18]


In [21]:
# return in a rank two array
z = x[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [22]:
z = np.copy(x[1:,2:])
# x[1:, 2:].copy()
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [23]:
indices = np.array([1,3])
print(indices)

[1 3]


In [25]:
y = x[indices,:]
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [26]:
z = x[:,indices]
print(z)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [28]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [27]:
z = np.diag(x)
print(z)

[ 1  7 13 19]


In [29]:
z = np.diag(x,k=1)
print(z)

[ 2  8 14 20]


In [30]:
z = np.diag(x,k=-1)
print(z)

[ 6 12 18]


In [32]:
x = np.array([[1,2,3],[5,2,8],[1,2,3]])
print(x)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [33]:
print(np.unique(x))

[1 2 3 5 8]


In [38]:
y = np.arange(1,25)
X = np.array([[y]])
print(y)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[1 2 3]
 [5 2 8]
 [1 2 3]]
